import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
    "on-primary-container": "var(--color-on-primary-container)",
    "primary-fixed-dim": "var(--color-primary-fixed-dim)",
    "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
    "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
    "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
    "surface-variant": "var(--color-surface-variant)",
    "on-secondary": "var(--color-on-secondary)",
    "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
    "inverse-on-surface": "var(--color-inverse-on-surface)",
    "tertiary-dim": "var(--color-tertiary-dim)",
    "tertiary": "var(--color-tertiary)",
    "on-surface": "var(--color-on-surface)",
    "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
    "surface-container-low": "var(--color-surface-container-low)",
    "secondary-dim": "var(--color-secondary-dim)",
    "on-tertiary-container": "var(--color-on-tertiary-container)",
    "surface-container-lowest": "var(--color-surface-container-lowest)",
    "on-error-container": "var(--color-on-error-container)",
    "surface-container": "var(--color-surface-container)",
    "surface-dim": "var(--color-surface-dim)",
    "secondary-fixed": "var(--color-secondary-fixed)",
    "primary-dim": "var(--color-primary-dim)",
    "secondary": "var(--color-secondary)",
    "on-background": "var(--color-on-background)",
    "inverse-surface": "var(--color-inverse-surface)",
    "on-secondary-container": "var(--color-on-secondary-container)",
    "surface-bright": "var(--color-surface-bright)",
    "inverse-primary": "var(--color-inverse-primary)",
    "on-error": "var(--color-on-error)",
    "outline-variant": "var(--color-outline-variant)",
    "background": "var(--color-background)",
    "on-surface-variant": "var(--color-on-surface-variant)",
    "on-secondary-fixed": "var(--color-on-secondary-fixed)",
    "outline": "var(--color-outline)",
    "surface-container-highest": "var(--color-surface-container-highest)",
    "secondary-container": "var(--color-secondary-container)",
    "error": "var(--color-error)",
    "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
    "on-primary-fixed": "var(--color-on-primary-fixed)",
    "primary-fixed": "var(--color-primary-fixed)",
    "tertiary-fixed": "var(--color-tertiary-fixed)",
    "surface-tint": "var(--color-surface-tint)",
    "surface-container-high": "var(--color-surface-container-high)",
    "tertiary-container": "var(--color-tertiary-container)",
    "on-tertiary": "var(--color-on-tertiary)",
    "on-primary": "var(--color-on-primary)",
    "surface": "var(--color-surface)",
    "primary": "var(--color-primary)",
    "primary-container": "var(--color-primary-container)",
    "error-dim": "var(--color-error-dim)",
    "error-container": "var(--color-error-container)"
},
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Manrope"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [forms, containerQueries],
}
