import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#3b002b",
        "tertiary-dim": "#882a69",
        "on-primary-container": "#0a0081",
        "tertiary-fixed-dim": "#ef81c4",
        "primary-dim": "#3939c7",
        "surface-container-low": "#f4eeff",
        "surface-container-high": "#e6deff",
        "on-secondary-fixed-variant": "#00655b",
        "error": "#b41340",
        "surface-variant": "#e1d8ff",
        "surface-bright": "#faf4ff",
        "outline": "#79719d",
        "on-background": "#302950",
        "on-surface": "#302950",
        "secondary-container": "#6df5e1",
        "on-secondary": "#c0fff3",
        "secondary-fixed-dim": "#5de7d3",
        "on-surface-variant": "#5e5680",
        "inverse-on-surface": "#a097c5",
        "on-tertiary-fixed-variant": "#6e1354",
        "primary-container": "#9396ff",
        "surface-container-highest": "#e1d8ff",
        "surface": "#faf4ff",
        "secondary-fixed": "#6df5e1",
        "secondary": "#00675d",
        "surface-dim": "#d8ceff",
        "on-secondary-container": "#005b51",
        "outline-variant": "#b0a7d6",
        "on-primary-fixed": "#000000",
        "tertiary": "#963776",
        "inverse-surface": "#0f072e",
        "surface-tint": "#4647d3",
        "tertiary-container": "#ff8ed2",
        "on-secondary-fixed": "#00463e",
        "primary-fixed-dim": "#8387ff",
        "error-dim": "#a70138",
        "on-tertiary": "#ffeef4",
        "error-container": "#f74b6d",
        "tertiary-fixed": "#ff8ed2",
        "on-primary-fixed-variant": "#0e009d",
        "inverse-primary": "#8083ff",
        "on-tertiary-container": "#63054a",
        "background": "#faf4ff",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#510017",
        "surface-container": "#ece4ff",
        "secondary-dim": "#005a50",
        "primary": "#4647d3",
        "on-primary": "#f4f1ff",
        "primary-fixed": "#9396ff",
        "on-error": "#ffefef"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Manrope"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [forms, containerQueries],
}
